# Generated by Django 3.1.7 on 2021-05-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Job', models.TextField()),
                ('Entry_Dates', models.DateField(auto_now_add=True, null=True)),
                ('Due_Dates', models.DateField()),
                ('Priority', models.CharField(choices=[('High', 'High'), ('Average', 'Average'), ('Low', 'Low')], default='', max_length=100)),
            ],
        ),
    ]
